### ISSUE TITLE
java.lang.AbstractMethodError after start app

### ISSUE THREAD

**Issue by kre0n** [git-as-svn/git-as-svn#484]
i used 3 use cases:
1. Installation on centos (Manual download) https://git-as-svn.github.io/git-as-svn/htmlsingle/git-as-svn.html#_manual_download
2. Installation on ubuntu (https://git-as-svn.github.io/git-as-svn/htmlsingle/git-as-svn.html#_installation_on_debianubuntu)
3. Clone git repository, compilation and run

In the first two cases, the application does not start. In the 3rd case the application starts, but -

I always get the same error

> Task :run
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
        at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:297)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
        at svnserver.Loggers.<clinit>(Loggers.kt:17)
        at svnserver.server.Main.<clinit>(Main.kt:27)
2022-01-27T18:08:07,059  INFO [misc] [main] (Main.kt:39) - git-as-svn version: , 2edb5d827d91e35b46324ed8224e5ca68f6b741e
2022-01-27T18:08:07,542  INFO [org.eclipse.jetty.server.Server] [main] (Server.java:383) - jetty-11.0.7; built: 2021-10-06T19:59:39.004Z; git: 389a3587725d94cc2470ed06aa184c6e57fe9ce8; jvm 17.0.1+12-Ubuntu-118.04
2022-01-27T18:08:07,606  INFO [org.eclipse.jetty.server.handler.ContextHandler] [main] (ContextHandler.java:901) - Started o.e.j.s.ServletContextHandler@7c18432b{/,null,AVAILABLE}
2022-01-27T18:08:07,616  INFO [org.eclipse.jetty.server.AbstractConnector] [main] (AbstractConnector.java:360) - Started ServerConnector@28a0fd6c{HTTP/1.1, (http/1.1)}{localhost:8123}
2022-01-27T18:08:07,617  INFO [org.eclipse.jetty.server.Server] [main] (Server.java:438) - Started Server@24f360b2{STARTING}[11.0.7,sto=0] @1150ms
2022-01-27T18:08:07,649  INFO [git] [main] (GitRepositoryConfig.kt:57) - [example]: using existing storage /home/ubuntu/git-as-svn/build/example.git
2022-01-27T18:08:07,794  INFO [web] [main] (WebServer.kt:100) - Registered servlet for path: /example.git/lfs_authenticate
2022-01-27T18:08:07,794  INFO [web] [main] (WebServer.kt:100) - Registered servlet for path: /example.git/info/lfs/objects/*
2022-01-27T18:08:07,795  INFO [web] [main] (WebServer.kt:100) - Registered servlet for path: /example.git/info/lfs/storage/*
2022-01-27T18:08:07,795  INFO [web] [main] (WebServer.kt:100) - Registered servlet for path: /example.git/info/lfs/locks/*
2022-01-27T18:08:07,834  INFO [git] [main] (GitBranch.kt:136) - [example@master]: loading cached revision changes: 2 revisions
2022-01-27T18:08:07,838  INFO [git] [main] (GitBranch.kt:148) - [example@master]: 2 cached revision loaded: 4 ms
2022-01-27T18:08:07,841  INFO [svn] [SvnServer] (SvnServer.kt:65) - Ready for connections on /0.0.0.0:3690
2022-01-27T18:09:57,502  INFO [svn] [SvnServer-thread-2] (SvnServer.kt:84) - New connection from: /[0:0:0:0:0:0:0:1]:47332
2022-01-27T18:09:57,519  INFO [svn] [SvnServer-thread-2] (SvnServer.kt:191) - Client: SVN/1.9.7 (x86_64-pc-linux-gnu)
2022-01-27T18:09:57,537  INFO [svn] [SvnServer-thread-2] (SvnServer.kt:244) - User: $anonymous
2022-01-27T18:09:57,580  INFO [svn] [SvnServer-thread-2] (SvnServer.kt:147) - Connection from /[0:0:0:0:0:0:0:1]:47332 closed
<==========---> 80% EXECUTING [15m 59s]
> :run

How to fix it?

**Comment by slonopotamus** [comment]
Fixed by 8885de1d0ef4b7535502fb1e54014b1ba4ab5deb
